import 'dotenv/config';
import servicesFactory from '../SERVICES/services.mjs';
import dataBaseLocal from '../DATA/dataBaseLocal.mjs';

async function run() {
  const to = process.env.TEST_BOOKING_EMAIL || process.env.CONTACT_EMAIL || '';
  if (!to) {
    console.error('Missing TEST_BOOKING_EMAIL (or CONTACT_EMAIL) in .env');
    process.exit(1);
  }

  const services = servicesFactory(dataBaseLocal());
  const booking = {
    name: process.env.TEST_BOOKING_NAME || 'Booking Test User',
    email: to,
    message:
      process.env.TEST_BOOKING_MESSAGE ||
      'This is a booking-service email test.',
    persons: Number(process.env.TEST_BOOKING_PERSONS || 2),
    date: process.env.TEST_BOOKING_DATE || '2026-03-30',
    time: process.env.TEST_BOOKING_TIME || '10:00',
    tourName: process.env.TEST_BOOKING_TOUR || 'Lisbon Whisper Test Tour',
    tourDescriptions:
      process.env.TEST_BOOKING_DESC ||
      'Test booking generated by script to validate email flow.',
  };

  console.log('Running booking service email test...');
  console.log(`Provider: ${process.env.EMAIL_PROVIDER || 'smtp'}`);
  console.log(`Customer email: ${booking.email}`);
  console.log(
    `Admin notice email: ${process.env.ADMIN_NOTICE_EMAIL || 'info@lisbonwhisper.com'}`
  );

  const result = await services.createBookingServices(booking);
  console.log('Booking service executed.');
  console.log(
    JSON.stringify(
      {
        bookingId: result?.id || result?._id || null,
        date: result?.date,
        time: result?.time,
        email: result?.email,
      },
      null,
      2
    )
  );
}

run().catch((err) => {
  console.error('Booking service email test failed.');
  console.error(err?.message || err);
  process.exit(1);
});
